apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: systems
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: systems
spec:
  gatewayClassName: systems
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces: {from: Same}
    {{- range $name, $app := (include "systems.webApps" . | fromYaml) }}
    - name: {{ $name }}-https
      hostname: {{ $app.hostname | quote }}
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - {kind: Secret, name: {{ $name }}-tls}
      allowedRoutes:
        namespaces: {from: Same}
    {{- end }}
{{- range $name, $app := (include "systems.webApps" . | fromYaml) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}-redirect
spec:
  parentRefs:
    - {name: systems, sectionName: http}
  hostnames: [{{ $app.hostname | quote }}]
  rules:
    - matches:
        - {method: GET}
        - {method: HEAD}
      filters:
        - type: RequestRedirect
          requestRedirect: {scheme: https, port: 443, statusCode: 301}
{{- if $app.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $name }}
spec:
  parentRefs:
    - {name: systems, sectionName: {{ $name }}-https}
  hostnames: [{{ $app.hostname | quote }}]
  rules:
    - backendRefs:
        - {name: {{ $name }}, port: 8000}
{{- end }}
{{- end }}
