postgresMigrationVerified: true
backgroundJobsEnabled: true
dailyReport:
  enabled: true
  suspend: false
  image: registry.digitalocean.com/freddierice-systems/daily-report@sha256:b5723d54de3659b5a74e07bb5298cdeffcff55a47bb7fccdae14b352302a8a2b
  sourceRevision: "ff9416c53129d754394c1a2b2e4a531605523602"
  printer:
    enabled: true
imagePullSecrets:
- name: freddierice-systems
apps:
  health:
    enabled: true
    image: registry.digitalocean.com/freddierice-systems/health@sha256:202db588945da8f711bf9ffe41474f34961aa52effbd58605c661c1eb6d98670
    sourceRevision: "2ad1b5626e42a5f2fa9f356ac9608b2208ea826a"
  trends:
    enabled: true
    image: registry.digitalocean.com/freddierice-systems/trends@sha256:2921b5fa49037d118e2557e1992657e4e4b8e454ad3089d94223f1b459adedbe
    sourceRevision: "e9bd3554aa3217cafadeff227e5779a709963d15"
