postgresMigrationVerified: true
backgroundJobsEnabled: true
dailyReport:
  enabled: true
  suspend: false
  image: registry.digitalocean.com/freddierice-systems/daily-report@sha256:b5723d54de3659b5a74e07bb5298cdeffcff55a47bb7fccdae14b352302a8a2b
  sourceRevision: "ff9416c53129d754394c1a2b2e4a531605523602"
  printer:
    enabled: true
imagePullSecrets:
- name: freddierice-systems
apps:
  health:
    enabled: true
    image: registry.digitalocean.com/freddierice-systems/health@sha256:202db588945da8f711bf9ffe41474f34961aa52effbd58605c661c1eb6d98670
    sourceRevision: "2ad1b5626e42a5f2fa9f356ac9608b2208ea826a"
  trends:
    enabled: true
    image: registry.digitalocean.com/freddierice-systems/trends@sha256:74ad786439bb7a49bd5efdd54275f25db0fdea616b1bd775383740a7178fb10c
    sourceRevision: "279c80fb13326b280ef4df4107a85dcf4dec0464"
