postgresMigrationVerified: true
backgroundJobsEnabled: true
dailyReport:
  enabled: true
  suspend: false
  web:
    enabled: true
  image: registry.digitalocean.com/freddierice-systems/daily-report@sha256:57e5e5fd62034658db30a77753fd65d5671d060fb37d549cc0f8671b64c880c8
  sourceRevision: "b32651ef84391f784900971a10497114fe34e885"
  printer:
    enabled: true
imagePullSecrets:
- name: freddierice-systems
apps:
  health:
    enabled: true
    image: registry.digitalocean.com/freddierice-systems/health@sha256:bda253b45779191d6972ccf8c8363b2a836692a9cd0826e0c9c5042b29d8ed44
    sourceRevision: "2db9112eb88e53290dc0bbae76db9fe00ae9873a"
  trends:
    enabled: true
    image: registry.digitalocean.com/freddierice-systems/trends@sha256:7fd84a4cd400dd51b7854675914c1603c810b8914cc7bbeefa89faabd95872d8
    sourceRevision: "7a111e691b7ea86e4a52c258d8fe15ad6bc1e7ca"
